# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class SubjectObsStevens(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    subject_group_name: str = Field(
        ...,
        description="⚠️ The use of a group with mixed subtypes could lead to unexpected results",
        title="Subject Group Name",
    )


class Filetype(str, Enum):
    csv = "csv"
    gpkg = "gpkg"
    geoparquet = "geoparquet"


class PersistStevensObservations(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filetypes: Optional[List[Filetype]] = Field(
        ["csv"], description="The output format", title="Filetypes"
    )
    filename_prefix: Optional[str] = Field(
        "observations",
        description="            Optional filename prefix to persist text to within the `root_path`.\n            We will always add a suffix based on the dataframe content hash to avoid duplicates.\n            ",
        title="Filename Prefix",
    )


class PersistDailySummaryStevens(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filename_prefix: Optional[str] = Field(
        "daily_summary",
        description="            Optional filename prefix to persist text to within the `root_path`.\n            We will always add a suffix based on the dataframe content hash to avoid duplicates.\n            ",
        title="Filename Prefix",
    )


class CreateHydrologicalReport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    template_path: str = Field(
        ...,
        description="Path or URL to the Word template (.docx) file with Jinja2 placeholders. Supports local paths and remote URLs (http://, https://).",
        title="Template Path",
    )


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class SpatialGrouper(RootModel[str]):
    root: str = Field(..., title="Spatial Regions")


class TemporalGrouper(RootModel[str]):
    root: str = Field(..., title="Time")


class ValueGrouper(RootModel[str]):
    root: str = Field(..., title="Category")


class Method(str, Enum):
    spline = "spline"


class SmoothingConfig(BaseModel):
    method: Literal["spline"] = Field(
        "spline",
        description="The smoothing method to apply. Currently supports 'spline'.",
        title="Method",
    )
    y_min: Optional[float] = Field(
        None,
        description="The minimum value to clamp smoothed values to. Useful for data like precipitation where values should not go below zero.",
        title="Y Min",
    )
    y_max: Optional[float] = Field(
        None,
        description="The maximum value to clamp smoothed values to.",
        title="Y Max",
    )
    resolution: Optional[int] = Field(
        10,
        description="The resolution multiplier for interpolation points. The number of output points will be len(x) * resolution.",
        title="Resolution",
    )
    degree: Optional[int] = Field(
        3,
        description="The degree of the spline. 1: Linear, 2: Quadratic, 3: Cubic (recommended), 4-5: Higher degree.",
        title="Degree",
    )


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")


class ErClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class Groupers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    groupers: Optional[List[Union[ValueGrouper, TemporalGrouper, SpatialGrouper]]] = (
        Field(
            None,
            description="            Specify how the data should be grouped to create the views for your dashboard.\n            This field is optional; if left blank, all the data will appear in a single view.\n            ",
            title=" ",
        )
    )


class DepthChart(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    smoothing: Optional[SmoothingConfig] = Field(
        None,
        description="Configuration for line smoothing. When set, creates a smoothed line with original data point markers.",
        title="Smoothing",
    )


class DoChart(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    smoothing: Optional[SmoothingConfig] = Field(
        None,
        description="Configuration for line smoothing. When set, creates a smoothed line with original data point markers.",
        title="Smoothing",
    )


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set Workflow Details",
    )
    time_range: Optional[TimeRange] = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    er_client_name: Optional[ErClientName] = Field(
        None, title="Select EarthRanger Data Source"
    )
    subject_obs_stevens: Optional[SubjectObsStevens] = Field(
        None, title="Get Subject Group Observations from EarthRanger"
    )
    groupers: Optional[Groupers] = Field(None, title="Set Groupers for Analysis")
    persist_stevens_observations: Optional[PersistStevensObservations] = Field(
        None, title="Persist Observations"
    )
    persist_daily_summary_stevens: Optional[PersistDailySummaryStevens] = Field(
        None, title="Persist Daily Summary"
    )
    depth_chart: Optional[DepthChart] = Field(None, title="Draw River Depth Chart")
    do_chart: Optional[DoChart] = Field(None, title="Draw DO Chart")
    create_hydrological_report: Optional[CreateHydrologicalReport] = Field(
        None, title="Create Hydrological Report"
    )
